import connectDB from './db';
import WalletData, { WalletDataDoc } from '@/app/models/WalletData';
import type { Transaction, StakeConversationTransaction } from '@/app/types/transactions';

/** Records a transaction (swap or stake conversation) against a specific wallet.
 * @param wallet - The wallet address to log the transaction against.
 * If no wallet is provided, it will log a general stake conversation.
 * @param tx 
 * The transaction details to log. This can be a swap transaction or a stake conversation.
 * @returns
 * A promise that resolves when the transaction is recorded.
 */

export async function recordTransaction(wallet: string, tx: Transaction): Promise<void> {
  if (!wallet) throw new Error("Wallet address is required for logging transaction");
  await connectDB();
  await WalletData.findOneAndUpdate(
    { wallet },
    { $push: { transactions: tx } },
    { upsert: true, new: true }
  );
}


/**
 * 
 * @param userInput : The user's input in the staking conversation.
 * @param response : The response generated by the system in the staking conversation.
 * Records a staking conversation entry without associating it with a specific wallet.
 * This is useful for logging general staking interactions that are not tied to a specific user wallet.
 * @returns A promise that resolves when the conversation is recorded.
 */

export async function recordStakeConversation(userInput: string, response: string): Promise<void> {
  await connectDB();
  const tx: StakeConversationTransaction = {
    id: `stake-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    type: 'stake',
    details: {
      userInput,
      response,
      timestamp: Date.now(),
    }
  };
  // Store in a general "stake" document, no wallet needed
  await WalletData.findOneAndUpdate(
    { wallet: null }, // filter: store all stake logs together
    { $push: { transactions: tx } },
    { upsert: true, new: true }
  );
}

/**
 * Fetches all transactions (both swap and stake conversations) for a specific wallet.
 * @param wallet - The wallet address to fetch transactions for.
 * @returns A promise that resolves to an array of transactions for the specified wallet.
 * If no transactions are found, it returns an empty array.
 */

export async function getTransactions(wallet: string): Promise<Transaction[]> {
  await connectDB();
  const data: WalletDataDoc | null = await WalletData.findOne({ wallet });
  return data?.transactions || [];
}

/**
 * @returns A promise that resolves to an array of all stake conversation transactions.
 * This function retrieves all stake conversation transactions that are not associated with any specific wallet.
 */

export async function getStakeConversations(): Promise<StakeConversationTransaction[]> {
  await connectDB();
  const data: WalletDataDoc | null = await WalletData.findOne({ wallet: null });
  if (!data) return [];
  // Only return transactions that look like StakeConversationTransaction
  return (data.transactions || []).filter(
    (tx: any): tx is StakeConversationTransaction =>
      tx.type === 'stake' &&
      tx.details &&
      typeof tx.details.userInput === 'string' &&
      typeof tx.details.response === 'string'
  );
}

